version: 2
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
      time: "04:00"
    commit-message:
      prefix: "Deps"

updates:
  - package-ecosystem: pip
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect


  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

