title = "Troubadix Ignore File"

[check_http_links_in_tags]
description = "Strings that should be ignored because they contain a valid URL type in a tag"
exclusions = [
            "The payloads try to open a connection to www.google.com",
            "The script attempts to connect to www.google.com",
            "to retrieve a web page from www.google.com",
            "Terms of use at https://www.verisign.com/rpa",
            "Subject: commonName=www.paypal.com",
            "example.com",
            "example.org",
            "www.exam",
            "sampling the resolution of a name (www.google.com)",
            "once with 'www.' and once without",
            "wget http://www.javaop.com/~ron/tmp/nc",
            "Ncat: Version 5.30BETA1 (http://nmap.org/ncat)",
            "as www.windowsupdate.com. (BZ#506016)",
            "located at http://sambarserver/session/pagecount.",
            "http://rest.modx.com",
            "ftp:// ",
            "ftp://'",
            "ftp://)",
            "ftp.c",
            "ftp.exe",
            "using special ftp://",
            "running ftp.",
            "ftp. The vulnerability",
            "'http://' protocol",
            "handle <a href='http://...'> properly",
            "Switch to git+https://",
            "wget https://compromised-domain.com/important-file",
            "the https:// scheme",
            "https://www.phishingtarget.com@evil.com",
            "distributions on ftp.proftpd.org have all been",
            "information from www.mutt.org:",
            "According to www.tcpdump.org:",
            "According to www.kde.org:",
            "From the www.info-zip.org site:",
            " (www.isg.rhul.ac.uk) for discovering this flaw and Adam Langley and",
            "Sorry about having to reissue this one -- I pulled it from ftp.gnu.org not",
            # e.g.:
            # Since gedit supports opening files via 'http://' URLs
            "'http://'",
            "'https://'",
            "http://internal-host$1 is still insecure",
            "http:// ",
            "https:// ",
            "such as 'http://:80'",
            "<http://localhost/moodle/admin/>",
            "https://username:password@proxy:8080",
            "sun.net.www.http.KeepAliveCache",
            "www.foo.com",
        ]

