name: Build and test Python package
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install and check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v3
        with:
          packages: troubadix tests
          python-version: ${{ matrix.python-version }}
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: |
          poetry run python -m unittest -v
        env:
          NASLINTER_DOCKER_RUN: 'true'
  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: '3.10'
      - name: Install codecov-python
        run: poetry run python -m pip install codecov
      - name: Run unit tests
        run: |
          poetry run coverage run -m unittest -v
        env:
          NASLINTER_DOCKER_RUN: 'true'
      - name: Create coverage XML report
        run: poetry run coverage xml
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
