name: Build and test Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    name: Linting
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install and check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v1
        with:
          packages: troubadix tests
          version: ${{ matrix.python-version }}

  test:
    name: Run all tests
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v1
        with:
          version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: |
          docker pull greenbone/ospd-openvas:stable # download image before running tests
          poetry run python -m unittest -v
        env:
          NASLINTER_DOCKER_RUN: "true"

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Download openvas!
        run: |
          docker pull greenbone/ospd-openvas:stable
      - name: Install and calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v1
        with:
          version: 3.8
