name: Container Image Builds for Old Linter

on:
  push:
    branches: [ main ]
    tags: ["v*"]
  workflow_dispatch:

env:
   REGISTRY: ghcr.io

jobs:
  images:
    name: Build and upload ospd-openvas container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Gather container image tags
        uses: greenbone/actions/container-image-tags@v1
        id: container
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: greenbone/actions/poetry@v1
      - name: Build wheel
        run: poetry build -f wheel
      - name: Build and push Container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.container.outputs.image-tags }}
          file: .docker/prod.Dockerfile
