name: Conventional Commits

on:
  pull_request:

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Report Conventional Commits
        uses: greenbone/actions/conventional-commits@v2
